### ISSUE TITLE
.NET 8 Error

### ISSUE THREAD

**Issue by CRC32EX** [nenoNaninu/Tapper#136]
# The problem
I can't use Tapper on .NET 8.

# Step to reproduce this issue.
1. Install Tapper.Generator
```
dotnet tool install --global Tapper.Generator
```

2. Initialize new project
```
dotnet new console --name Test
cd Test
```

3. Install Tapper.Attributes
```
dotnet add package Tapper.Attributes
```

4. Edit code
```cs
// Program.cs
using Tapper;

namespace Test;

[TranspilationSource]
public class User
{
  public uint Id { get; set; }
  public string Name { get; set; }
}
```

5. Run tapper
```
tapper --project Test.csproj --output outDir
```

# Error
```
> tapper --project Test.csproj --output outDir
Start loading the csproj of C:\Users\user01\Desktop\Test\Test.csproj.
Create Compilation...
======== Exception ========
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Tapper.DefaultTypeMapperProvider..ctor(Compilation compilation, Boolean includeReferencedAssemblies) in /home/runner/work/Tapper/Tapper/src/Tapper/DefaultTypeMapperProvider.cs:line 37
   at Tapper.App.TranspileCore(Compilation compilation, String outputDir, NewLineOption newLine, Int32 indent, Boolean referencedAssembliesTranspilation, SerializerOption serializerOption, NamingStyle namingStyle, EnumStyle enumStyle) in /home/runner/work/Tapper/Tapper/src/Tapper.Generator/App.cs:line 90
   at Tapper.App.Transpile(String project, String output, NewLineOption newLine, Int32 indent, Boolean assemblies, SerializerOption serializer, NamingStyle namingStyle, EnumStyle enum) in /home/runner/work/Tapper/Tapper/src/Tapper.Generator/App.cs:line 50
```

# My Environment
- Windows 11
- Visual Studio Communitty 2022 17.8.0
```
> dotnet --version
8.0.100

> dotnet --list-sdks
8.0.100 [C:\Program Files\dotnet\sdk]

> dotnet tool list --global
tapper.generator      1.8.4      tapper
```

- Tapper.Attributes 1.8.4

**Comment by nenoNaninu** [comment]
Plz show `dotnet --list-sdks` results.

**Comment by CRC32EX** [comment]
```
> dotnet --list-sdks
8.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by nenoNaninu** [comment]
Please keep .NET 7 installed along with .NET 8 for a while. I will support .NET 8 soon.

**Comment by nenoNaninu** [comment]
Tapper supports .NET 8 from v1.9.0. Try it!
