### ISSUE TITLE
Handling partial classes

### ISSUE THREAD

**Issue by thisisclint21** [nenoNaninu/Tapper#98]
Hi,

Apparently partial classes are not handled.

```
 me@clint21.dev  ~/Projects/Prototypes/CodenameVolga/api tapper --project api.csproj --output outdir

Start loading the csproj of /Users/me/Projects/Prototypes/CodenameVolga/api/api.csproj.
Create Compilation...
======== Exception ========
System.ArgumentException: An item with the same key has already been added. Key: Volga.Entities.Hits.Hit
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
```

**Comment by nenoNaninu** [comment]
I released Tapper v1.8.3, which supports C# partial classes. Try it!

**Comment by thisisclint21** [comment]
You can count on me!
